steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/toolbox', '-f', 'src/main/docker/Dockerfile.jvm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/toolbox']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'toolbox', 
  '--image', 'gcr.io/$PROJECT_ID/toolbox', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--allow-unauthenticated',
  '--service-account', 'toolbox@toolbox-289508.iam.gserviceaccount.com'
  ]
images:
- gcr.io/$PROJECT_ID/toolbox